---
  - name: install apt-transport-https
    apt: pkg=apt-transport-https state=present
  
  - name: add plasticscm sources
    template: src=plastic-sources dest=/etc/apt/sources.list
  
  - name: add plasticscm key 1
    shell: wget https://www.plasticscm.com/plasticrepo/plasticscm-common/{{plasticscm_distro}}/Release.key -O - | sudo apt-key add -
  
  - name: add plasticscm key 2
    shell: wget https://www.plasticscm.com/plasticrepo/plasticscm-latest/{{plasticscm_distro}}/Release.key -O - | sudo apt-key add -
  
  - name: add plasticscm key 3
    shell: wget https://www.plasticscm.com/plasticrepo/plasticscm-stable/{{plasticscm_distro}}/Release.key -O - | sudo apt-key add -
  
  - name: apt-get update again
    shell: apt-get -y update
  
  - name: install plasticscm-server-complete
    apt: pkg=plasticscm-server-complete state=present
  
  - name: create plasticscm data dir
    shell: mkdir -p {{plasticscm_data_dir}}
  
  - name: create plasticscm conf dir
    shell: mkdir -p {{plasticscm_conf_dir}}
  
  - name: set plasticscm data dir
    template: src=db.conf dest=/opt/plasticscm5/server/db.conf
  
  - name: copy plasticscm config files
    shell: cp /opt/plasticscm5/server/*.conf {{plasticscm_conf_dir}}/
  
  - name: restart plasticscm
    shell: /usr/sbin/service plasticsd restart
