---
  - name: install apt-transport-https
    apt: pkg=apt-transport-https state=present
  
  - name: add plasticscm sources
    template: src=templates/plastic-sources dest=/etc/apt/sources.list
  
  - name: add plasticscm key 1
    shell: wget https://www.plasticscm.com/plasticrepo/plasticscm-common/Ubuntu_14.04/Release.key -O - | sudo apt-key add -
  
  - name: add plasticscm key 2
    shell: wget https://www.plasticscm.com/plasticrepo/plasticscm-latest/Ubuntu_14.04/Release.key -O - | sudo apt-key add -
  
  - name: add plasticscm key 3
    shell: wget https://www.plasticscm.com/plasticrepo/plasticscm-stable/Ubuntu_14.04/Release.key -O - | sudo apt-key add -
  
  - name: apt-get update again
    shell: apt-get -y update
  
  - name: install plasticscm-server-complete
    apt: pkg=plasticscm-server-complete state=present
